welcome_message: (anything/[ENTER])
date_format: (full/mmddyy/daydd)
uptime_format: (null/days/hours/colon)
memory_format: (<percent/values/both>, <GB/MiB>)
pf_result: (CPU/RAM)
should_display_image: (true/false)
should_display_blocks: (true/false)
should_display_text: (true/false)
should_display_keys: (true/false)
color_block_node: (anything/[ENTER])
space_before: (number)
space_after: (number)
lines_before: (number)
lines_after: (number)
hr_divider_node: (anything/[ENTER])
hr_node_repeat: (number)
default_bullet: (anything/[ENTER])
interface_bullet: (anything/[ENTER])
machine_bullet: (anything/[ENTER])
shell_bullet: (anything/[ENTER])
cpu_bullet: (anything/[ENTER])
ram_bullet: (anything/[ENTER])
uptime_bullet: (anything/[ENTER])
date_bullet: (anything/[ENTER])
word_wrap: (number)
user_string_color: (color)
machine_string_color: (color)
hr_color: (color)
detail_key_color: (color)
detail_value_color: (color)
text_description_color: (color)
default_bullet_color: (color)
interface_bullet_color: (color)
machine_bullet_color: (color)
shell_bullet_color: (color)
cpu_bullet_color: (color)
ram_bullet_color: (color)
uptime_bullet_color: (color)
date_bullet_color: (color)
interface_override: (anything/[ENTER])
machine_override: (anything/[ENTER])
shell_override: (anything/[ENTER])
cpuram_override: (true/false)
uptime_override: (true/false)
date_override: (true/false)